version: "3.8"

services:
  # Backend da aplicação
  app:
    build: ./backend
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=app_db

  # Banco de dados MySQL da aplicação
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3308:3306" # porta externa 3308 para evitar conflito
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # SonarQube
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar_db
    networks:
      - sonar-network

  # Banco de dados do SonarQube
  sonar_db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - sonar-network

# Volumes persistentes
volumes:
  mysql_data:
  sonar_db_data:

# Redes separadas para evitar conflitos
networks:
  app-network:
  sonar-network:
