version: "3.8"

services:
  app:
    build: ./backend
    container_name: app
    ports:
      - "8164:3000"  
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=appsenha
      - DB_NAME=app_db
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "8165:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appsenha
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "8166:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar_db
    networks:
      - sonar-network
    restart: always

  sonar_db:
    image: postgres:13
    container_name: sonar_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - sonar-network
    restart: always

volumes:
  mysql_data:
    name: app_mysql_data
  sonar_db_data:
    name: app_sonar_db_data

networks:
  app-network:
    name: app_network
  sonar-network:
    name: app_sonar_network
