version: "3.8"

services:
  app:
    build: ./backend
    container_name: leo-app
    ports:
      - "8164:3000"  
    depends_on:
      - mysql
    networks:
      - leo-network
    environment:
      - DB_HOST=leo-mysql
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=appsenha
      - DB_NAME=app_db
    restart: always

  mysql:
    image: mysql:8
    container_name: leo-mysql
    ports:
      - "8165:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appsenha
    volumes:
      - leo_mysql_data:/var/lib/mysql
    networks:
      - leo-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  sonarqube:
    image: sonarqube:latest
    container_name: leo-sonarqube
    ports:
      - "8166:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://leo-sonar-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar_db
    networks:
      - leo-sonar-network
    restart: always

  sonar_db:
    image: postgres:13
    container_name: leo-sonar-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - leo_sonar_db_data:/var/lib/postgresql/data
    networks:
      - leo-sonar-network
    restart: always

volumes:
  leo_mysql_data:
    name: leo_mysql_data
  leo_sonar_db_data:
    name: leo_sonar_db_data

networks:
  leo-network:
    name: leo_network
  leo-sonar-network:
    name: leo_sonar_network
