version: "3.8"

services:
  app:
    build: ./backend
    ports:
      - "8167:3000"
    depends_on:
      - leo-mysql
    networks:
      - leo-network
    environment:
      - DB_HOST=leo-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=app_db
    restart: always
    command: ["./wait-for.sh", "leo-mysql", "3306", "npm", "start"]

  leo-mysql:
    container name: leo-mysql
    image: mysql:8.0
    ports:
      - "8165:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
    volumes:
      - leo_mysql_data:/var/lib/mysql
    networks:
      - leo-network
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://leo-sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - leo-sonar-db
    networks:
      - leo-sonar-network
    restart: always

  leo-sonar-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - leo_sonar_db_data:/var/lib/postgresql/data
    networks:
      - leo-sonar-network
    restart: always

volumes:
  leo_mysql_data:
  leo_sonar_db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  leo-network:
  leo-sonar-network:
